# https://symfony.com/doc/current/components/cache.html

framework:
  cache:
    pools:
      cache.my_redis:
        adapter: cache.adapter.redis
        provider: app.my_custom_redis_provider

services:
  app.my_custom_redis_provider:
    class: \Redis
    factory: [ 'Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection' ]
    arguments:
      - 'redis://localhost'
      - { retry_interval: 2, timeout: 5 }
