# https://symfony.com/doc/current/doctrine.html
# https://www.doctrine-project.org/projects/doctrine-orm/en/3.3/index.html

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: '%env(DB_DRIVER)%'
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'
        server_version: '%env(DB_VERSION)%'

        mapping_types:
          enum: string

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    metadata_cache_driver:
      type: service
      id: doctrine.system_cache_provider
    query_cache_driver:
      type: service
      id: doctrine.system_cache_provider
    result_cache_driver:
      type: service
      id: doctrine.result_cache_provider
    controller_resolver:
      auto_mapping: false
      enabled: false
    mappings:
      User:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/User/Infrastructure/Database/ORM'
        prefix: 'App\User\Domain\Entity'
        alias: User
      Acl:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Acl/Infrastructure/Database/ORM'
        prefix: 'App\Acl\Domain\Entity'
        alias: Acl
      Workspace:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Workspaces/Infrastructure/Database/ORM'
        prefix: 'App\Workspaces\Domain\Entity'
        alias: Workspace
      Channel:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Channels/Infrastructure/Database/ORM'
        prefix: 'App\Channels\Domain\Entity'
        alias: Channel
      Board:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Boards/Infrastructure/Database/ORM'
        prefix: 'App\Boards\Domain\Entity'
        alias: Channel
      Message:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Messages/Infrastructure/Database/ORM'
        prefix: 'App\Messages\Domain\Entity'
        alias: Message

#when@test:
#  doctrine:
#    dbal:
#      # "TEST_TOKEN" is typically set by ParaTest
#      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
