# https://www.doctrine-project.org/projects/doctrine-migrations/en/3.8/index.html

doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'App\Shared\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Database/Migrations'
  enable_profiler: '%kernel.debug%'
  storage:
    table_storage:
      table_name: 'migration_versions'
