monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - app # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - activity # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: [ "!event" ]
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      app:
        type: stream
        path: "%kernel.logs_dir%/app-%kernel.environment%.log"
        level: notice
        channels: [ "app" ]
        formatter: monolog.formatter.json
        process_psr_3_messages: false
      activity:
        type: stream
        path: "%kernel.logs_dir%/activity-%kernel.environment%.log"
        level: info
        channels: [ "activity" ]
        formatter: monolog.formatter.json
        process_psr_3_messages: false
        max_files: 14

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]
      deprecation:
        type: stream
        channels: [ deprecation ]
        path: php://stderr
        formatter: monolog.formatter.json
      app:
        type: stream
        path: "%kernel.logs_dir%/app-%kernel.environment%.log"
        level: notice
        channels: [ "app" ]
        formatter: monolog.formatter.json
        process_psr_3_messages: false
      activity:
        type: stream
        path: "%kernel.logs_dir%/activity-%kernel.environment%.log"
        level: info
        channels: [ "activity" ]
        formatter: monolog.formatter.json
        process_psr_3_messages: false
        max_files: 14
