# https://symfony.com/bundles/NelmioApiDocBundle/current/index.html

nelmio_api_doc:
  use_validation_groups: true
  type_info: true
  documentation:
    info:
      title: Publisher API
      description: API for publishing books and more
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
  areas: # to filter documented areas
    path_patterns:
      - ^/api/v1
  html_config:
    assets_mode: 'cdn'
