# https://symfony.com/bundles/NelmioApiDocBundle/current/index.html

#app.swagger:
#  path: /api/doc.json
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger }

app.redocly:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.redocly }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
