kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: attribute

### JWT AUTH
api_refresh_token:
  path: /api/auth/v1/refresh-token

api_login_check:
  path: /api/auth/v1/token

### Domains controller
user:
  resource: ../src/User/Infrastructure/Controller/
  type: attribute

shared:
  resource: ../src/Shared/Infrastructure/Controller/
  type: attribute
