kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: attribute

### JWT AUTH
api_refresh_token:
  path: /api/auth/v1/refresh-token

api_login_check:
  path: /api/auth/v1/token

### Domains controller
shared:
  resource: ../src/Shared/Presentation/Controller/
  type: attribute

user:
  resource: ../src/User/Presentation/Controller/
  type: attribute

channel:
  resource: ../src/Channels/Presentation/Controller/
  type: attribute

workspace:
  resource: ../src/Workspaces/Presentation/Controller/
  type: attribute

acl:
  resource: ../src/Acl/Presentation/Controller/
  type: attribute

oauth:
  resource: ../src/Oauth/Presentation/Controller/
  type: attribute
