kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: attribute

### JWT AUTH
api_refresh_token:
  path: /api/auth/v1/refresh-token

api_login_check:
  path: /api/auth/v1/token

### Domains controller
shared:
  resource: ../src/Shared/Infrastructure/Controller/
  type: attribute

user:
  resource: ../src/User/Infrastructure/Controller/
  type: attribute

channel:
  resource: ../src/Channels/Infrastructure/Controller/
  type: attribute

workspace:
  resource: ../src/Workspaces/Infrastructure/Controller/
  type: attribute
