services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Resource\Fixtures\:
    resource: '%kernel.project_dir%/tests/Resource/Fixtures/*'
    tags:
      - { "name": "doctrine.fixture.orm" }

  App\Shared\Infrastructure\Bus\CommandBus:
    public: true

  App\Shared\Infrastructure\Bus\QueryBus:
    public: true

  App\Shared\Infrastructure\Bus\EventBus:
    public: true

  App\Skills\Domain\Factory\:
    resource: '../src/Skills/Domain/Factory'
    public: true
