filebeat.inputs:
  - type: log
    paths:
      - /var/log/dev.log
  - type: log
    paths:
      - /var/log/handling.log

output.logstash:
  hosts: ["logstash_cont:5044"]
  index: "log-app"

#setup.ilm.enabled: false
#setup.template.overwrite: true
#setup.template.name: "symfony-loggitos"
#setup.template.pattern: "symfony-loggitos-*"
#
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  index: "logs-symfony"
##  #username: "filebeat_internal"
##  #password: "YOUR_PASSWORD"
